### ISSUE TITLE
Floating input sizes Implementation

### ISSUE THREAD

**Issue by EtagiBI** [karolzak/keras-unet#32]
Hello,

Is it possible to somehow implement a floating input sizes in custom Keras Unet (custom_vnet.py)? 
For instance, I have images of different shapes: 1024x1024x3, 3072x3072x3, 512x512x3. If I use a fixed input, I have to severely downsample bigger images loosing quality and important features.

As far as I know, for floating image sizes it's recommended to use `(None, None, channels)` as an input shape, but I doubt it's enough...

**Comment by karolzak** [comment]
Hi @EtagiBI 
I don't think it's technically possible to fit images of different sizes into the same model (unless you resize/cropp them to uniform size first). Could you please point to any examples of that approach implemented or explained in detail somewhere?

> As far as I know, for floating image sizes it's recommended to use (None, None, channels) as an input shape, but I doubt it's enough...

If I remember correctly, using `(None, None, channels)` as input shape for your network will only make it accept images of any size as an input batch but still all the images within the batch should have the same size.  
For example: to fit your input images into a single numpy array all of them need to be of the same size so you can end up with shape like `(num_images, height, width, channels)`. Now if you would really want to have a numpy array with images of different size (basically a nested list) you would have a final shape of `(num_images, )` and you wouldn't be able to fit it into the model as it would expect a shape of `(num_images, height, width, channels)`

```
ValueError: Error when checking input: expected input_6 to have 4 dimensions, but got array with shape (6, 1)
```

**Comment by EtagiBI** [comment]
Thanks for your reply!

From what I know It's technically possible, although there's no official guide for this. [Here're](https://stats.stackexchange.com/a/445201) some tips from J Trana on StackOverflow:

> 1) Set the input of the network to allow for a variable size input using "None" as a placeholder dimension on the input_shape. See Francois Chollet's answer [here](https://github.com/keras-team/keras/issues/1920#issuecomment-193883690).
> 2) Use convolutional layers only until a global pooling operation has occurred (e.g. GlobalMaxPooling2D). Then Dense layers etc. can be used because the size is now fixed.
> 3) Use a batch size of 1 only. This avoids dealing with mixed sizes within a batch.
> 4) Write a small custom Sequence that creates batches of size 1 from the list of inputs. I did this to avoid dealing with different sizes inside a single Numpy array.
> 5) Use Model.fit_generator on your custom Sequence for training and validation. (v.s. Model.fit)
> 6) For some reason, Model.predict_generator popped even when using the Sequence as above. I had to resort to using Model.predict on individual inputs.

I wonder if it's possible to implement this approach with custom Keras Unet from your repository. I'm confused by tip #2, because there're no Global pooling layers in Unet.

**Comment by karolzak** [comment]
Hmm, this makes sense and you're right - technically it should work.

> I'm confused by tip #2, because there're no Global pooling layers in Unet.   

As you noticed there's no global pooling layers in U-Net architecture however there are no dense layers either so the overall model is fully convolutional and thus I think it should not care about input height/width size.

I have many concerns though regarding if this "hack" makes sense at all:
- `batch_size` needs to be 1 - which may vastly affect training performance in terms of learning speed, model convergence and accuracy
- output prediction masks size won't be uniform - they will always adapt to the input size
- it's questionable if such model will work equally well for all the image sizes?

All up I see little to no advantages in using variable size images as input vs downsizing them to some fixed size. If anything this brings concerns and unnecessary complexity.  
In scenarios where downsizing images is not feasible (due to potential loss of information), e.g. if you're working with satellite images which in general come in quite a huge resolutions - you would rather cut your big images into smaller ones. So following the example you shared in your first comment:
> I have images of different shapes: 1024x1024x3, 3072x3072x3, 512x512x3. If I use a fixed input, I have to severely downsample bigger images loosing quality and important features.

In my preprocessing code I would simply take these larger images and cut them into smaller pieces to fit them into some uniform size that my model will be trained on. For example:
1024x1024x3 -> 4 images of size 512x512x3
3072x3072x3 -> 9 images 1024x1024x3 -> 36 images 512x512x3

There are some helper functions in `utils` which help you with this:
- [generating patches/crops](https://github.com/karolzak/keras-unet#get-smaller-patchescrops-from-bigger-image)
- [plot patches/crops](https://github.com/karolzak/keras-unet#plot-small-patches-into-single-big-image)
- [stitch patches back into the bigger image](https://github.com/karolzak/keras-unet#reconstruct-a-bigger-image-from-smaller-patchescrops)

**Comment by EtagiBI** [comment]
Thanks for sharing your point!

I should definitely try this patching->plotting technique.
