### ISSUE TITLE
Inputs don't match Outputs

### ISSUE THREAD

**Issue by leedrake5** [karolzak/keras-unet#6]
I've been working on this, and just can't get it to work. It can't matching inputs to outputs. 

Input data: two folders of images (400 x 400 pixels) in a master folder called TrainingData

```
import tensorflow as tf
config = tf.ConfigProto()
config.gpu_options.allow_growth=True
sess = tf.Session(config=config)

from keras.preprocessing.image import ImageDataGenerator
from keras import models
from keras_unet.models import custom_unet

model = custom_unet(
input_shape=(400, 400, 3),
use_batch_norm=False,
num_classes=2,
filters=64,
dropout=0.2,
output_activation='sigmoid')


from keras.utils import multi_gpu_model
#parallel_model = multi_gpu_model(model, gpus=4, cpu_merge=True, cpu_relocation=True)
parallel_model = multi_gpu_model(model, gpus=4)


train_datagen = ImageDataGenerator(rescale = 1./255,
shear_range = 0.2,
zoom_range = 0.2,
horizontal_flip = True,
validation_split = 0.2)

train_generator = train_datagen.flow_from_directory(
    '<path>/TrainingData',
    target_size=(400, 400),
    batch_size=32,
    class_mode='binary',
    shuffle=True,
    subset='training')

validation_generator = train_datagen.flow_from_directory(
    '<path>/TrainingData',
    target_size=(400, 400),
    batch_size=32,
    class_mode='binary',
    shuffle=True,
    subset='validation')
    
from keras.callbacks import ModelCheckpoint
filepath="<newpath>/Unetweights.best.hdf5"
checkpoint = ModelCheckpoint(filepath, monitor='val_acc', verbose=1, save_best_only=True, mode='max')
callbacks_list = [checkpoint]

from collections import Counter
counter = Counter(train_generator.classes)
max_val = float(max(counter.values()))
class_weights = {class_id : max_val/num_images for class_id, num_images in counter.items()}

parallel_model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['acc'])

history=parallel_model.fit_generator(train_generator,
steps_per_epoch = train_generator.samples // 32,
validation_data = validation_generator,
validation_steps = validation_generator.samples // 32,
epochs = 75,
class_weight=class_weights, callbacks=callbacks_list)
```

I get the following error:

> Epoch 1/75
> Traceback (most recent call last):
>   File "<stdin>", line 6, in <module>
>   File "/home/bly/anaconda3/envs/tf_gpu/lib/python3.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
>     return func(*args, **kwargs)
>   File "/home/bly/anaconda3/envs/tf_gpu/lib/python3.7/site-packages/keras/engine/training.py", line 1418, in fit_generator
>     initial_epoch=initial_epoch)
>   File "/home/bly/anaconda3/envs/tf_gpu/lib/python3.7/site-packages/keras/engine/training_generator.py", line 217, in fit_generator
>     class_weight=class_weight)
>   File "/home/bly/anaconda3/envs/tf_gpu/lib/python3.7/site-packages/keras/engine/training.py", line 1211, in train_on_batch
>     class_weight=class_weight)
>   File "/home/bly/anaconda3/envs/tf_gpu/lib/python3.7/site-packages/keras/engine/training.py", line 789, in _standardize_user_data
>     exception_prefix='target')
>   File "/home/bly/anaconda3/envs/tf_gpu/lib/python3.7/site-packages/keras/engine/training_utils.py", line 128, in standardize_input_data
>     'with shape ' + str(data_shape))
> ValueError: Error when checking target: expected conv2d_38 to have 4 dimensions, but got array with shape (32, 1)

I honestly don't know what I am doing wrong.

**Comment by karolzak** [comment]
Hi @leedrake5 !

I successfully reproduced this problem on my machine and I'm the problem seems to be with how you create data generators and more specifically how you create your label masks.

> ValueError: Error when checking target: expected conv2d_38 to have 4 dimensions, but got array with shape (32, 1)

Above error msg indicates that on your last layer it expects target (output/Y) to have a shape of 4 dimensions, e.g. `(batch_size, height, width, num_classes)` - according to your code I'd say it should be `(32, 400, 400, 2)` while it seems you are providing it with target (Y) values of shape `(32, 1)` which is because when you are using `ImageDataGenerator` you are setting `class_mode` param to `binary` and thus for each input 400x400x3 image it generates a single binary value of 0 or 1.
Best way to see it for yourself is to do something like below after you create your generators:
```python
sample_batch = next(train_generator)
print('Shape of input images in a batch:', sample_batch[0].shape)
print('Shape of input segmentation masks in a batch:', sample_batch[1].shape)
```
And it should output something like this:
```output
Shape of input images in a batch: (32, 400, 400, 3)
Shape of input segmentation masks in a batch: (32,)
```

### In order to create a proper data generator for image segmentation task you need to do something similar to this:

Assume folders structure as below:
```
train
  |--img
  |  |--class_1 
  |    |--img1.jpg
  |    |--img2.jpg
  |    |--img3.jpg
  |    …
  |--masks
  |  |--class_1
  |    |--img1.png
  |    |--img2.png
  |    |--img3.png
  |    …
```
Then run this code:
```python
data_gen_args = dict(width_shift_range=0.2, height_shift_range=0.2)
image_datagen = ImageDataGenerator(**data_gen_args)
mask_datagen = ImageDataGenerator(**data_gen_args)
seed = 1
target_size = (400,400)
batchsize = 8

image_generator = image_datagen.flow_from_directory(
    'train/img',
    target_size=target_size,
    class_mode=None, 
    seed=seed,
    batch_size=batchsize, 
    color_mode='rgb')

mask_generator = mask_datagen.flow_from_directory(
    'train/masks', 
    target_size=target_size,
    class_mode=None, 
    seed=seed, 
    batch_size=batchsize, 
    color_mode='grayscale')

train_generator = zip(image_generator, mask_generator)
```
And validate all the shapes in a sample batch:
```output
Shape of input images in a batch: (8, 400, 400, 3)
Shape of input segmentation masks in a batch: (8, 400, 400, 1)
```

It's quite well explained in [this thread](https://github.com/keras-team/keras/issues/3059#issuecomment-364787723)

Also, in case you want to have a multiclass segmentation you need to provide a proper mask that would reflect that (multilayer, each layer represents a single class) and use `num_classes` param on `custom_unet` function.

Let me know if that makes sense or in case you have more questions.
Cheers!

**Comment by leedrake5** [comment]
Thanks @karolzak! This is perfect and explains what I was doing wrong. I though it had to be data loading somehow, but wasn't sure what was wrong.
